package proxy

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"sort"
	"strconv"
	"strings"
)

// maxAssertsPerEntry bounds the flattened JSON asserts for one response; very
// large bodies fall back to an exact-body assertion instead.
const maxAssertsPerEntry = 200

// GenerateHurl renders recorded traffic as a Hurl (https://hurl.dev) test
// file asserting the main (legacy) server's behavior. The file uses a
// {{base_url}} variable so the same suite runs against any deployment of the
// new app:
//
//	hurl --test --variable base_url=http://localhost:8082 tests.hurl
//
// JSON responses are flattened into per-field jsonpath asserts, matching the
// proxy's structural comparison (key order and formatting don't matter).
// Other bodies are asserted byte-exactly.
//
// Only read requests (GET/HEAD) are exported: they can be replayed any number
// of times without side effects. Write endpoints need a different strategy.
func GenerateHurl(records []RequestRecord) string {
	var b strings.Builder
	b.WriteString("# Regression tests generated by strangler-fig-proxy from recorded production traffic.\n")
	b.WriteString("# Each entry asserts the legacy server's observed behavior.\n")
	b.WriteString("#\n")
	b.WriteString("# Run with:\n")
	b.WriteString("#   hurl --test --variable base_url=http://localhost:8082 tests.hurl\n")
	b.WriteString("#\n")
	b.WriteString("# Note: JSON asserts verify every recorded field; fields *added* by the new\n")
	b.WriteString("# app are not detected here, only by the proxy's live comparison.\n")

	for _, record := range records {
		entry, ok := hurlEntry(record)
		if !ok {
			continue
		}
		b.WriteString("\n")
		b.WriteString(entry)
	}

	return b.String()
}

func hurlEntry(record RequestRecord) (string, bool) {
	if record.Method != http.MethodGet && record.Method != http.MethodHead {
		return "", false
	}
	if record.MainStatus == 0 {
		return "", false
	}

	url := record.URLPath
	if record.QueryParams != "" {
		url += "?" + record.QueryParams
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# recorded request id=%d\n", record.ID)
	fmt.Fprintf(&b, "%s {{base_url}}%s\n", record.Method, url)
	fmt.Fprintf(&b, "HTTP %d\n", record.MainStatus)

	body := record.MainBody
	if record.Method == http.MethodHead || body == "" {
		return b.String(), true // status-only assertion
	}

	if asserts, ok := jsonAsserts(body); ok {
		b.WriteString("[Asserts]\n")
		for _, assert := range asserts {
			b.WriteString(assert)
			b.WriteString("\n")
		}
		return b.String(), true
	}

	writeExactBodyAssert(&b, body)
	return b.String(), true
}

// jsonAsserts flattens a JSON body into per-field jsonpath assertions. It
// returns ok=false when the body is not JSON, is too large to flatten, or
// contains keys that can't be safely embedded in a jsonpath expression; the
// caller then falls back to an exact body assert.
func jsonAsserts(body string) ([]string, bool) {
	decoder := json.NewDecoder(bytes.NewReader([]byte(body)))
	decoder.UseNumber() // preserve the exact number representation
	var parsed interface{}
	if err := decoder.Decode(&parsed); err != nil {
		return nil, false
	}

	asserts, ok := flattenJSON("$", parsed)
	if !ok || len(asserts) == 0 || len(asserts) > maxAssertsPerEntry {
		return nil, false
	}
	return asserts, true
}

func flattenJSON(path string, value interface{}) ([]string, bool) {
	switch v := value.(type) {
	case map[string]interface{}:
		// Sort keys for deterministic output.
		keys := make([]string, 0, len(v))
		for key := range v {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		var asserts []string
		for _, key := range keys {
			if !isSafeJSONPathKey(key) {
				return nil, false
			}
			child, ok := flattenJSON(path+"['"+key+"']", v[key])
			if !ok {
				return nil, false
			}
			asserts = append(asserts, child...)
		}
		return asserts, true
	case []interface{}:
		asserts := []string{fmt.Sprintf("jsonpath \"%s\" count == %d", path, len(v))}
		for i, item := range v {
			child, ok := flattenJSON(fmt.Sprintf("%s[%d]", path, i), item)
			if !ok {
				return nil, false
			}
			asserts = append(asserts, child...)
		}
		return asserts, true
	case string:
		return []string{fmt.Sprintf("jsonpath \"%s\" == %s", path, hurlString(v))}, true
	case json.Number:
		return []string{fmt.Sprintf("jsonpath \"%s\" == %s", path, v.String())}, true
	case bool:
		return []string{fmt.Sprintf("jsonpath \"%s\" == %t", path, v)}, true
	case nil:
		return []string{fmt.Sprintf("jsonpath \"%s\" == null", path)}, true
	default:
		return nil, false
	}
}

// isSafeJSONPathKey reports whether a key can be embedded verbatim in
// single-quoted jsonpath bracket notation inside a double-quoted Hurl
// string. Quotes, backslashes, and control characters would need two layers
// of escaping with murky semantics, so bodies with such keys fall back to an
// exact body assert instead.
func isSafeJSONPathKey(key string) bool {
	for _, r := range key {
		if r == '\'' || r == '"' || r == '\\' || r < 0x20 {
			return false
		}
	}
	return true
}

// hurlString renders a Go string as a quoted Hurl string literal. Hurl string
// escapes match JSON's, so this reuses the JSON encoder.
func hurlString(s string) string {
	encoded, err := json.Marshal(s)
	if err != nil {
		return `""`
	}
	return string(encoded)
}

// writeExactBodyAssert emits a byte-exact body assertion. A multiline string
// block's content spans up to the closing fence, so it can only represent
// bodies that end with a newline; everything else (and bodies containing
// fences) uses Hurl's base64 body, which is exact for arbitrary bytes.
func writeExactBodyAssert(b *strings.Builder, body string) {
	if strings.HasSuffix(body, "\n") && !strings.Contains(body, "```") {
		b.WriteString("```\n")
		b.WriteString(body)
		b.WriteString("```\n")
		return
	}

	fmt.Fprintf(b, "base64,%s;\n", base64.StdEncoding.EncodeToString([]byte(body)))
}

// handleHurlAPI exports recorded read traffic as a Hurl test file.
//
// Query parameters:
//   - path:  url_path prefix filter (e.g. /api/users)
//   - limit: max test entries after deduplication (default 50, max 500)
func (h *Handler) handleHurlAPI(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", "GET")
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	limit := 50
	if v := r.URL.Query().Get("limit"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 && n <= 500 {
			limit = n
		}
	}

	query := `
		SELECT id, timestamp, method, url_path, query_params, request_headers, request_body,
		       main_status, main_headers, main_body, main_response_time_ms,
		       new_status, new_headers, new_body, new_response_time_ms,
		       responses_match, mismatch_type, served_by
		  FROM requests
		 WHERE method IN ('GET', 'HEAD') AND main_status > 0`
	var args []interface{}
	if prefix := r.URL.Query().Get("path"); prefix != "" {
		query += ` AND url_path LIKE ? || '%'`
		args = append(args, prefix)
	}
	query += ` ORDER BY id DESC`

	rows, err := h.database.db.Query(query, args...)
	if err != nil {
		slog.Error("failed to query requests for hurl export", "error", err)
		http.Error(w, "failed to query requests", http.StatusInternalServerError)
		return
	}
	defer rows.Close()

	// Keep only the most recent record per unique request so repeated
	// requests don't produce duplicate tests.
	seen := map[string]bool{}
	var records []RequestRecord
	for rows.Next() && len(records) < limit {
		record, err := scanRequestRecord(rows)
		if err != nil {
			continue
		}
		key := record.Method + " " + record.URLPath + "?" + record.QueryParams
		if seen[key] {
			continue
		}
		seen[key] = true
		records = append(records, record)
	}

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	if _, err := w.Write([]byte(GenerateHurl(records))); err != nil {
		slog.Debug("failed to write hurl response", "error", err)
	}
}
